from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATASET_PATH = PROJECT_ROOT / "data" / "preferences.jsonl"
OUTPUTS_DIR = PROJECT_ROOT / "outputs"
TRAIN_OUTPUT_DIR = OUTPUTS_DIR / "dpo_checkpoints"

MODEL_NAME = "sshleifer/tiny-gpt2"
BETA = 0.1

MAX_LENGTH = 256
MAX_PROMPT_LENGTH = 128

LEARNING_RATE = 5e-5
NUM_TRAIN_EPOCHS = 1
PER_DEVICE_TRAIN_BATCH_SIZE = 1
GRADIENT_ACCUMULATION_STEPS = 4
LOGGING_STEPS = 1
SAVE_STEPS = 10
WARMUP_STEPS = 0
WEIGHT_DECAY = 0.01